// front-svelte/src/pages/Login.svelte
<!-- src/pages/Login.svelte -->
<script lang="ts">
    import { token, userId } from '../stores/auth';
    import { apiFetch } from '../services/api';
    import { push } from 'svelte-spa-router';
    import { writable } from 'svelte/store';

    let email = '';
    let password = '';
    const error = writable('');

    async function handleLogin() {
        error.set('');
        try {
            const data = await apiFetch('/login', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ email, password }),
            });
            token.set(data.token);
            const payload = JSON.parse(atob(data.token.split('.')[1]));
            userId.set(payload.userId);
            push('/users');
        } catch (err) {
            if (err instanceof Error) {
                error.set(err.message);
            } else {
                error.set('An unknown error occurred');
            }
        }
    }
</script>

<form on:submit|preventDefault={handleLogin}>
    <h2>Login</h2>
    {#if $error}
        <p style="color: red;">{$error}</p>
    {/if}
    <div>
        <label for="email">Email:</label>
        <input id="email" type="email" bind:value={email} required />
    </div>
    <div>
        <label for="password">Password:</label>
        <input id="password" type="password" bind:value={password} required />
    </div>
    <button type="submit">Login</button>
</form>

// front-next/src/app/login/page.tsx
// app/login/page.tsx
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '../../hooks/useAuth';
import apiClient from '../../lib/apiClient';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const { login } = useAuth();
  const router = useRouter();
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    try {
      const response = await apiClient.post('/login', { email, password });
      const token = response.data.token;
      login(token);
      router.push('/users');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } catch (err: any) {
      setError(err.response?.data?.error || 'Login failed');
    }
  };

  return (
    <div>
      <h2>Login</h2>
      {error && <p style={{ color: 'red' }}>{error}</p>}
      <form onSubmit={handleSubmit}>
        <div>
          <label>Email:</label>
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
          />
        </div>
        <div>
          <label>Password:</label>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
          />
        </div>
        <button type="submit">Login</button>
      </form>
    </div>
  );
}
