// front-svelte/src/pages/UserList.svelte
<!-- src/pages/UserList.svelte -->
<script lang="ts">
    import { onMount } from 'svelte';
    import { apiFetch } from '../services/api';
    import { push } from 'svelte-spa-router';
    import { userId as loggedInUserId } from '../stores/auth';

    interface User {
    id: number;
    name: string;
    }

    let users: User[] = [];
    let error = '';

    onMount(async () => {
    try {
        users = await apiFetch('/users');
    } catch (err) {
        if (err instanceof Error) {
            error = err.message;
        } else {
            error = String(err);
        }
    }
    });

    function handleUserClick(id: number) {
    push(`/users/${id}/items`);
    }
</script>

<h2>User List</h2>
{#if error}
    <p style="color: red;">{error}</p>
{/if}
<ul>
    {#each users as user}
        <li>
            <button type="button" on:click={() => handleUserClick(user.id)} style="cursor: pointer;">
                {user.name} {user.id === $loggedInUserId ? '(You)' : ''}
            </button>
        </li>
    {/each}
</ul>

// front-react/src/components/UserList.tsx
import React, { useEffect, useState } from 'react';
import apiClient from '../utils/apiClient';
import { useNavigate } from 'react-router-dom';

interface User {
    id: number;
    name: string;
}

interface UserListProps {
    userId: number; // Logged-in user's ID
}

const UserList: React.FC<UserListProps> = ({ userId }) => {
    const [users, setUsers] = useState<User[]>([]);
    const navigate = useNavigate();

    const fetchUsers = async () => {
        try {
            const response = await apiClient.get('/users');
            setUsers(response.data);
        } catch (error) {
            console.error('Failed to fetch users', error);
        }
    };

    useEffect(() => {
        fetchUsers();
    }, []);

    const handleUserClick = (userId: number) => {
        navigate(`/users/${userId}/items`);
    };

    return (
        <div style={{ padding: '16px' }}>
            <h2>User List</h2>
            <ul>
                {users.map((user) => (
                    <li
                        key={user.id}
                        onClick={() => handleUserClick(user.id)}
                        style={{
                            padding: '8px',
                            marginBottom: '8px',
                            border: '1px solid #ccc',
                            cursor: 'pointer',
                            borderRadius: '4px',
                        }}
                    >
                        {user.name} {user.id === userId && "(You)"}
                    </li>
                ))}
            </ul>
        </div>
    );
};

export default UserList;
